/*
// do not edit; automatically generated by 'make testconfig' in vhci-hcd sourcedir
#define USB_VHCI_HCD_VERSION "1.15"
#define USB_VHCI_HCD_DATE "2016-10-25"
#define USB_VHCI_IOCIFC_VERSION "1.15"
#define USB_VHCI_IOCIFC_DATE USB_VHCI_HCD_DATE
//#define OLD_GIVEBACK_MECH
//#define OLD_DEV_BUS_ID
//#define NO_DEV_INIT_NAME
//#define NO_HAS_TT_FLAG
// end of file
*/

#ifndef EVEUSB_CONFIG_H
#define EVEUSB_CONFIG_H

#include <linux/version.h>

#if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,26)
  #define NO_HAS_TT_FLAG
  #define OLD_DEV_BUS_ID /* static inline const char *dev_name(struct device *dev) */
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,23)
  #define OLD_GIVEBACK_MECH
#endif

//#if LINUX_VERSION_CODE < KERNEL_VERSION(2,?,??)
//  #define NO_DEV_INIT_NAME
//#endif

#endif // EVEUSB_CONFIG_H
