#!/bin/sh

case $1 in
        start)
                ifconfig eth0 192.168.10.200 netmask 255.255.252.0
                route add default gw 192.168.11.1
                echo "nameserver 114.114.114.114" > /etc/resolv.conf
               
                ;;
        stop)
                ;;
        *)
                exit 1
                ;;
esac
