# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS drdynvc-client video-client urbdrc-client urbdrc-client-libusb smartcard-client serial-client remdesk-client rdpsnd-client rdpsnd-client-oss rdpsnd-client-fake rdpgfx-client rdpei-client rdpdr-client rdp2tcp-client rail-client parallel-client geometry-client encomsp-client echo-client drive-client disp-client cliprdr-client audin-client audin-client-oss ainput-client freerdp-client)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target drdynvc-client
add_library(drdynvc-client STATIC IMPORTED)

# Create imported target video-client
add_library(video-client STATIC IMPORTED)

# Create imported target urbdrc-client
add_library(urbdrc-client STATIC IMPORTED)

# Create imported target urbdrc-client-libusb
add_library(urbdrc-client-libusb STATIC IMPORTED)

# Create imported target smartcard-client
add_library(smartcard-client STATIC IMPORTED)

# Create imported target serial-client
add_library(serial-client STATIC IMPORTED)

# Create imported target remdesk-client
add_library(remdesk-client STATIC IMPORTED)

# Create imported target rdpsnd-client
add_library(rdpsnd-client STATIC IMPORTED)

# Create imported target rdpsnd-client-oss
add_library(rdpsnd-client-oss STATIC IMPORTED)

# Create imported target rdpsnd-client-fake
add_library(rdpsnd-client-fake STATIC IMPORTED)

# Create imported target rdpgfx-client
add_library(rdpgfx-client STATIC IMPORTED)

# Create imported target rdpei-client
add_library(rdpei-client STATIC IMPORTED)

# Create imported target rdpdr-client
add_library(rdpdr-client STATIC IMPORTED)

# Create imported target rdp2tcp-client
add_library(rdp2tcp-client STATIC IMPORTED)

# Create imported target rail-client
add_library(rail-client STATIC IMPORTED)

# Create imported target parallel-client
add_library(parallel-client STATIC IMPORTED)

# Create imported target geometry-client
add_library(geometry-client STATIC IMPORTED)

# Create imported target encomsp-client
add_library(encomsp-client STATIC IMPORTED)

# Create imported target echo-client
add_library(echo-client STATIC IMPORTED)

# Create imported target drive-client
add_library(drive-client STATIC IMPORTED)

# Create imported target disp-client
add_library(disp-client STATIC IMPORTED)

# Create imported target cliprdr-client
add_library(cliprdr-client STATIC IMPORTED)

# Create imported target audin-client
add_library(audin-client STATIC IMPORTED)

# Create imported target audin-client-oss
add_library(audin-client-oss STATIC IMPORTED)

# Create imported target ainput-client
add_library(ainput-client STATIC IMPORTED)

# Create imported target freerdp-client
add_library(freerdp-client STATIC IMPORTED)

set_target_properties(freerdp-client PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:drdynvc-client>;\$<LINK_ONLY:remdesk-client>;\$<LINK_ONLY:rdpsnd-client>;\$<LINK_ONLY:rdpdr-client>;\$<LINK_ONLY:rdp2tcp-client>;\$<LINK_ONLY:rail-client>;\$<LINK_ONLY:encomsp-client>;\$<LINK_ONLY:cliprdr-client>;\$<LINK_ONLY:video-client>;\$<LINK_ONLY:urbdrc-client>;\$<LINK_ONLY:rdpsnd-client>;\$<LINK_ONLY:rdpgfx-client>;\$<LINK_ONLY:rdpei-client>;\$<LINK_ONLY:geometry-client>;\$<LINK_ONLY:echo-client>;\$<LINK_ONLY:disp-client>;\$<LINK_ONLY:audin-client>;\$<LINK_ONLY:ainput-client>;\$<LINK_ONLY:smartcard-client>;\$<LINK_ONLY:serial-client>;\$<LINK_ONLY:parallel-client>;\$<LINK_ONLY:drive-client>;\$<LINK_ONLY:urbdrc-client-libusb>;\$<LINK_ONLY:rdpsnd-client-oss>;\$<LINK_ONLY:rdpsnd-client-fake>;\$<LINK_ONLY:audin-client-oss>;\$<LINK_ONLY:freerdp>;\$<LINK_ONLY:winpr>;winpr"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/FreeRDP-ClientTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "freerdp" "winpr" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
