# eveusb - USB Network Gate daemon
#
# USB Network Gate allows you to share USB devices with remote computers
# and easily connect to shared devices at the remote side.

# This file should be copied to /etc/init.

description	"USB Network Gate daemon"
author		"Electronic Team, Inc. <support@electronic.us>"

start on runlevel [2345]
stop on runlevel [016]

# setuid eveusb
kill timeout 30

exec /opt/ElectronicTeam/eveusb/bin/eveusbd --process

pre-start script
	modprobe eveusb
end script
